spring:
  application:
    name: spring-payment-soap

  datasource:
    url: jdbc:mysql://localhost:3306/wo_soap_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  port: 8090
